#! /bin/sh
# prerm script for libpms-cil-doc
#
# see: dh_installdeb(1)

set -e

MXML=`pkg-config monodoc --variable=sourcesdir`/../monodoc.xml
MSRC=`pkg-config monodoc --variable=sourcesdir`/pms.source

case "$1" in
	remove|upgrade)
		if [ -x /usr/bin/pms-monodoc ]; then
            pms-monodoc -i "$MXML" -o "$MXML" -s "$MSRC" -r
		fi
	;;
	deconfigure)
	;;
	failed-upgrade)
	;;
	*)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
