.\" 
.\" pms-monodoc manual page.
.\" (C) 2004 - 2008 Matthew Metnetsky <matthew@cowarthill.com
.\"
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.TH pms-monodoc 1

.SH NAME
pms-monodoc \- install/uninstall documentation from monodoc 

.SH SYNOPSIS
.B pms-monodoc path/to/monodoc.xml [install|uninstall]

.SH AUTHOR
Matthew Metnetsky <matthew@cowarthill.com>

.SH WEB SITE
http://www.cowarthill.com/
