.\" 
.\" pms2-repo-split manual page.
.\" (C) 2004 - 2009 Matthew Metnetsky <matthew@cowarthill.com
.\"
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.TH pms2-repo-split 1

.SH NAME
pms2-repo-split \- split repository.xml to .pmx and .pmc given an output path

.SH SYNOPSIS
.B pms2-repo-split repository output:/etc/libpms2/[project]

.SH AUTHOR
Matthew Metnetsky <matthew@cowarthill.com>

.SH WEB SITE
http://www.cowarthill.com/
