.\" 
.\" pms2-repo-upgrade manual page.
.\" (C) 2004 - 2009 Matthew Metnetsky <matthew@cowarthill.com
.\"
.de Sp \" Vertical space (when we can't use .PP)
.if t .sp .5v
.if n .sp
..
.TH pms2-repo-upgrade 1

.SH NAME
pms2-repo-upgrade \- upgrade .pmx or repository.xml files to the latest supported formats

.SH SYNOPSIS
.B pms2-repo-upgrade repository [output]

.SH AUTHOR
Matthew Metnetsky <matthew@cowarthill.com>

.SH WEB SITE
http://www.cowarthill.com/
