ASSEMBLY = PMS.dll
TARGET = library

KEYFILE = ../PMS.snk

LIBRARIES =  \
		-pkg:printgroove-liblog4net2.0 \
		-r:Npgsql \
		-r:System \
		-r:System.Configuration \
		-r:System.Data

-include ../build/rules.mk
