#!/usr/bin/env python

import os
import sys
import stat
import traceback
import shutil
import tempfile
import time

from optparse import OptionParser
from commands import getoutput

class Config:
    def __init__(self):
        self.config = {}
        self.op = OptionParser(version='%prog N/A', conflict_handler='resolve')
        self.op.disable_interspersed_args()
        self.op.add_option('-l', dest='local', help='Modify $USER PMS providers', action='store_true')
        self.op.add_option('-r', dest='remove', help='Remove provider', action='store_true')
        self.op.add_option('-c', dest='create', help='Create provider', action='store_true')
        self.config, self.remainder = self.op.parse_args()
        if os.name != 'nt':
            self.provider = '/etc/libpms2/providers'
        else:
            self.provider = 'c:\\Program Files\\Common Files\\PMS\\etc\\providers'

    def remove(self):
        return self.config.remove

    def create(self):
        return self.config.create

    def local(self):
        return self.config.local


def exit(val):
    sys.exit(val)

def get_type_nt(val):
    t = val.split(',')
    ret = os.popen('c:\\GTK\\2.8\\bin\\gacco.exe -e ' + t[1])
    p = ret.readlines()
    ret.close()

    if 'not found in the Microsft Global' in p[0]:
        return None

    return "%s, %s" % (t[0], str(p[0]).strip())


def ensure_file(cfg, mode='r'):
    if not os.access(cfg.provider, os.F_OK):
        return False
    try:
        open(cfg.provider, mode).close()
        return True
    except:
        return False

def ensure_dir(cfg):
    if not os.access(os.path.dirname(cfg.provider), os.F_OK):
        try:
            os.mkdir(os.path.dirname(cfg.provider))
        except:
            print("mkdir(%s) failed" % (os.path.dirname(cfg.provider)))
            exit(1)

def get_type(val):
    t = val.split(',')
    p = getoutput('gacutil /l ' + t[1]).split("\n")
    t = [x.strip() for x in t]
    p = [x.strip() for x in p]
    pl = len(p)
    tl = len(t)

    if p[pl-1].endswith("0"):
        return None

    # find highest because we're not specific
    if not tl > 2:
        return "%s, %s" % (t[0], str(p[pl-2]))

    # find best match
    matches = []
    for i in range(1, pl-1):
        parts = p[i].split(',')
        parts = [x.strip() for x in parts]
        for y in range(2, tl):
            #print("gacuti %d = %s" % (y-1, parts[y-1]))
            #print("search %d = %s" % (y, t[y]))
            if parts[y-1].startswith(t[y]):
                matches.append(p[i])
    return "%s, %s" % (t[0], str(matches[len(matches)-1]))

def list_providers(cfg):
    if not ensure_file(cfg, 'r'):
        print('could not read: %s' % (cfg.provider))
        exit(0)
    f = open(cfg.provider, 'r')
    for line in f:
        print(line.strip())
    f.close()

def add_provider(cfg):
    if len(cfg.remainder) != 2:
        print "Usage: %s [options] name 'type, assembly'" % (cfg.op.get_prog_name())
        exit(1)

    if os.name != 'nt':
        type = get_type(cfg.remainder[1])
    else:
        type = get_type_nt(cfg.remainder[1])

    if type is None:
        print("Assembly '%s' not found in GAC" % (cfg.remainder[1]))
        exit(1)

    ensure_dir(cfg)
    if not ensure_file(cfg, 'a+'):
        print('could not edit/create: %s' % (cfg.provider))
        exit(0)

    f = open(cfg.provider, 'a+')
    for line in f:
        line = line.strip()

        if line.startswith(';') or line.startswith('#') or line == '':
            pass

        if line.startswith(cfg.remainder[0] + ' = '):
            print("provider already contains key '%s'" % (cfg.remainder[0]))
            f.close()
            exit(1)

    f.write("%s = %s\n" % (cfg.remainder[0], type))
    f.close()

def remove_provider(cfg):
    if len(cfg.remainder) != 1:
        print("Usage: %s -r name" % (cfg.op.get_prog_name()))
        exit(1)

    if not ensure_file(cfg, 'r+'):
        print('could not open for writing: %s' % (cfg.provider))
        exit(1)

    tmp = os.path.join(tempfile.gettempdir(), 'pms2-providers')

    f = open(cfg.provider, 'r')
    t = open(tmp, 'w')

    for line in f:
        line = line.strip()

        if not line.startswith(cfg.remainder[0] + ' = '):
            t.write(line + "\n")

    f.close()
    t.close()
	
    if os.name != 'nt':
        mode = stat.S_IMODE(os.stat(cfg.provider)[stat.ST_MODE])
        shutil.move(tmp, cfg.provider)
        os.chmod(cfg.provider, mode)
    else:
        shutil.move(tmp, cfg.provider)


if __name__ == '__main__':
    cfg = Config()

    if not cfg.remove() and not cfg.create():
        list_providers(cfg)
    elif cfg.create():
        add_provider(cfg)
    elif cfg.remove():
        remove_provider(cfg)
    else:
        print("unsupported commands")
        exit(1)
